version: "2"
services:

  zookeeper-1:
    container_name: zookeeper-1    
    networks: ["vnet"]
    hostname: zookeeper-1.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 1 3 vnet

  zookeeper-2:
    container_name: zookeeper-2    
    networks: ["vnet"]
    hostname: zookeeper-2.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 2 3 vnet

  zookeeper-3:
    container_name: zookeeper-3    
    networks: ["vnet"]
    hostname: zookeeper-3.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 3 3 vnet

  kafka-1:
    container_name: kafka-1    
    networks: ["vnet"]
    hostname: kafka-1.vnet
    image: smizy/kafka:0.10-alpine
 

networks:
  vnet:
    external:
      name: vnet 
